Repository Merck/simtrial, pull requests merged in 2024-05, with the labels that each got.

#237 236 milestone take the un squared version of the current z statistics
  R/milestone.R
  man/milestone.Rd
  tests/testthat/test-unvalidated-multitest.R
Labels: functionality development

#240 Update news for simtrial 0.4.0
  DESCRIPTION
  NEWS.md
  man/simtrial-package.Rd
Labels: CRAN

#229 Enable different tests per cutting for `sim_gs_n()`
  DESCRIPTION
  R/maxcombo.R
  R/milestone.R
  R/rmst.R
  R/sim_fixed_n.R
  R/sim_gs_n.R
  R/wlr.R
  man/maxcombo.Rd
  man/milestone.Rd
  man/sim_gs_n.Rd
  man/wlr.Rd
  tests/testthat/helper-sim_gs_n.R
  tests/testthat/test-unvalidated-rmst.R
  tests/testthat/test-unvalidated-sim_gs_n.R
Labels: functionality development

#248 Run roxygen2
  man/sim_gs_n.Rd
Labels: chore
